name: '[PRT] Quality Engineering'

on:
  pull_request_target:
    branches:
      - main
      - master
    types:
      - labeled

jobs:
  quality-engineering:
    name: QE
    uses: vtex-apps/usqa/.github/workflows/quality-engineering.yml@v2
    with:
      danger: true
      dangerRequireChangelog: false
      dotnetLint: true
      dotnetSonar: true
      dotnetSonarProjectKey: vtex-apps_cybersource-fraud
      dotnetSonarOrganization: vtex-apps
      cypress: false
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      sonarToken: ${{ secrets.SONAR_TOKEN }}
      cypressJson: ${{ secrets.VTEX_QE }}
